### ISSUE TITLE
dlib 설치 오류

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team11#2]
Windows 10 환경에서 `pip install dlib`를 하면 오류가 나면서 설치되지 않습니다. cmake 등 기타 구성요소는 모두 제대로 설치했는데도 그렇고 반복적으로 시도해도 똑같았습니다. 이 문제를 해결하기 위해 검색해봤는데, `pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f` 로 설치하니까 오류없이 잘 설치되었습니다. 아마 dlib의 버전 문제인 것 같습니다. 이 문제를 해결하고 쉽게 설치할 수 있도록 README.md를 수정해주시면 감사하겠습니다.

**Error Logs**
```
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py): started
  Building wheel for dlib (setup.py): finished with status 'error'
  ERROR: Complete output from command 'c:\program files (x86)\microsoft visual studio\shared\python36_64\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MY\\AppData\\Local\\Temp\\pip-install-w_rq9gi4\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MY\AppData\Local\Temp\pip-wheel-fjg94mos' --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 403, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 997, in _execute_child
      startupinfo)
  FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 129, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 125, in get_cmake_version
      "\n*******************************************************************\n")
  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************
  
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib: started
    Running setup.py install for dlib: finished with status 'error'
    ERROR: Complete output from command 'c:\program files (x86)\microsoft visual studio\shared\python36_64\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MY\\AppData\\Local\\Temp\\pip-install-w_rq9gi4\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MY\AppData\Local\Temp\pip-record-qq6hu8se\install-record.txt' --single-version-externally-managed --compile --user --prefix=:
    ERROR: running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\setup.py", line 125, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    ----------------------------------------
ERROR: Command "'c:\program files (x86)\microsoft visual studio\shared\python36_64\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MY\\AppData\\Local\\Temp\\pip-install-w_rq9gi4\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MY\AppData\Local\Temp\pip-record-qq6hu8se\install-record.txt' --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\MY\AppData\Local\Temp\pip-install-w_rq9gi4\dlib\
```

**Comment by xogus1107** [comment]
read me 수정되었습니다.

**Comment by xogus1107** [comment]
read me 수정되었습니다.
